### PR TITLE
parse_h.pl fixed for #53 and updates against GDAL 3.7.3 (and 3.6/3.8.2)

### PR DESCRIPTION
**Pull request by fpl**
This fixes the metaprogramming script that generates a partial `FFI.pm` module. Here included is a simple unified diff that gives evidence of fixing #53 but also could point to other changes (presumably 3.7 is that used in 0.11+). 
I even run against 3.6.2 (the current version in Debian 12 stable), but another fix is due for 3.8.2 where something seems create problems to the parse script. 
What is not clear to me currently is how the FFI binding can take care of changes in the C API from multiple versions. Maybe @ajolma can clarify this aspect: it is intended to create one version for every minor version of GDAL, or what?

PS: note that this also takes care of removing of string_pointer use.

### CODE REVIEW

**Comment by fpl** [comment]
This is the udiff of the resulting FFI attaches.

[original_vs_3.6.2.txt](https://github.com/ajolma/Geo-GDAL-FFI/files/13739652/original_vs_3.6.2.txt)

**Comment by ajolma** [comment]
The GDAL C API should be very stable in the case of existing functions. New versions only add new functions to the API.

**Comment by fpl** [comment]
> The GDAL C API should be very stable in the case of existing functions. New versions only add new functions to the API.

That what I also thought, but in 3.6 -> 3.7 some void funcs became int returning ones. What I wonder about anyway is: what happens with FFI if one tries to attach non existing funcs because he's using a previous version of GDAL ?

**Comment by fpl** [comment]
About the 3.8.2 final update, I still would consider that a draft, because a series of funcs needs to be verified for pointer-vs-array (e.g. the RPC related ones probably) via C API documentation.

**Comment by fpl** [comment]
I'm identifying the funcs to be changed for take arrays in considerations, instead of pointers. Of course, it is a good idea to add new tests for new funcs, which could be not so immediate. 
Another question for @ajolma: is there any reason to skip the whole set of funcs into `alg/gdal_alg.h` in the bindings generation?

**Comment by ajolma** [comment]
I don't think there's any other reason than it requires work. It hasn't been included so far as I didn't have a good enough reason.

**Comment by fpl** [comment]
In the latest revision, I updated it for 3.8.2 WITH screening for arrays vs pointers on the basis of the GDAL doc, including the gdal_alg.h header. I'm also including here the diff against the master output (which is based on 3.7).

[original_vs_3.8.2.txt](https://github.com/ajolma/Geo-GDAL-FFI/files/13829370/original_vs_3.8.2.txt)

**Comment by fpl** [comment]
Uhm, but for fixing some divergences with the master, my idea about this is: 
- providing tests for algorithmic functions and possibly other functions. That should also work as documentation because their use is not so clear.

**Comment by shawnlaffan** [comment]
This PR contains a number of changes that are now on the master branch, as well as having several conflicts due to other PRs that have been merged recently.  It might be simpler to close this and cherry pick (or recreate) the relevant commits to a new branch.  

The tests you mention might also be better done as a separate PR.

**Comment by fpl** [comment]
> This PR contains a number of changes that are now on the master branch, as well as having several conflicts due to other PRs that have been merged recently. It might be simpler to close this and cherry pick (or recreate) the relevant commits to a new branch.
> 
> The tests you mention might also be better done as a separate PR.

Speaking of which, I'm afraid your commit 19026411130bdb00a71ae195842bc5f19511966e in the Makefile.PL to get data from Alien seems needing to be reinstated in master :-( Not sure it is a fault by me, or what: I'm quite sure I always used rebasing, maybe a sane pull at some point in time would have been safer...   




> This PR contains a number of changes that are now on the master branch, as well as having several conflicts due to other PRs that have been merged recently. It might be simpler to close this and cherry pick (or recreate) the relevant commits to a new branch.
> 
> The tests you mention might also be better done as a separate PR.

**Comment by shawnlaffan** [comment]
> Speaking of which, I'm afraid your cmt number 19026411130bdb00a71ae195842bc5f19511966e in ajolma repo in the Makefile.PL to get data from Alien seems needing to be reinstated in master :-( Not sure it is a fault by me, or what: I'm quite sure I always used rebasing, maybe a sane pull at some point in time would have been safer...

The master branch on Github shows this commit is still in place.  Have you been updating your master branch from the repo before running the rebase commands against it?

**Comment by shawnlaffan** [comment]
Something has become disconnected with all the rebasing.  This PR currently contains 32 commits, most of which are already on master.

It would perhaps be simpler if you could generate a new PR based on current master, cherry-picking the relevant commits across.

**Comment by fpl** [comment]
Ok, I'm closing this PR and update for GDAL 3.9 possibly.

**Comment by shawnlaffan** [comment]
Thanks @fpl.  It will be good to have the parsing changes on master as they will simplify future maintenance.

**Pull request closed without merging**
