### PR TITLE
Added tests for issue #53, followup to PR #57.

### PR DESCRIPTION
**Pull request by fpl**
Hi,

Here I added a few tests for issue #53, still missing a test for  `OCTTransformBounds` because I honestly did not understand the use and context of that API function. Without PR 57, those tests should cause a failure due to wrong type of arguments (double[] instead of double*) i.e. argument type not a reference to scalar.
. 

If you try to force the use of double *, that should cause a segfault in the Perl interpreter.

Cheers

PS: note that this PR does not include the fix proposed in #57, so the obvious failures indicated above are expected and present in the CI failures.

### CODE REVIEW

**Comment by shawnlaffan** [comment]
It is probably cleaner to append these changes to PR #57?

**Comment by fpl** [comment]
> It is probably cleaner to append these changes to PR #57?

I merged the previous PR #57 into this one for coherence.

**Comment by shawnlaffan** [comment]
Thank you for combining the commits.  It seems, though, that something has happened to the commit authors of several commits in the merge process.  

It might be necessary to rebase your commits onto the master branch and then force push the PR.  If it all gets too messy then a new PR might be simpler.  And if that's too complex (as rebasing can be) then I can also cherry-pick your commits onto a new PR.

**Comment by shawnlaffan** [comment]
Although the authors seem correct when pulling the changes locally so perhaps don't worry about the rebase.

**Comment by shawnlaffan** [comment]
@fpl - I added some comments a while ago but it seems one has to publish them so they are visible to others.  I have just done that so now you should hopefully be able to see them.  If you don't have time then I can clean them up in a later commit.

**Comment by fpl** [comment]
> @fpl - I added some comments a while ago but it seems one has to publish them so they are visible to others. I have just done that so now you should hopefully be able to see them. If you don't have time then I can clean them up in a later commit.

Yep, I can change the test code as suggested.

**Comment by shawnlaffan** [comment]
> Yep, I can change the test code as suggested.

Thanks @fpl.  If you can rebase the changes on latest master then that would be useful.  If it causes problems then don't worry about it.

**Comment by fpl** [comment]
I'm closing because this is obsoleted by PR #68

**Pull request closed without merging**
